sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ndomanyo/docker-tutorial-complex-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ndomanyo/docker-tutorial-complex-client-test npm test

after_success:
  - docker build -t ndomanyo/docker-tutorial-complex-client ./client
  - docker build -t ndomanyo/docker-tutorial-complex-nginx ./nginx
  - docker build -t ndomanyo/docker-tutorial-complex-server ./server
  - docker build -t ndomanyo/docker-tutorial-complex-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ndomanyo/docker-tutorial-complex-client
  - docker push ndomanyo/docker-tutorial-complex-nginx
  - docker push ndomanyo/docker-tutorial-complex-server
  - docker push ndomanyo/docker-tutorial-complex-worker
