language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t ndomanyo/docker-tutorial-complex-react-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t ndomanyo/docker-tutorial-complex-client ./client
  - docker build -t ndomanyo/docker-tutorial-complex-nginx ./nginx
  - docker build -t ndomanyo/docker-tutorial-complex-server ./server
  - docker build -t ndomanyo/docker-tutorial-complex-worker ./worker
