name: Deploy MultiDocker
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]



jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t ndomanyo/docker-tutorial-complex-react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true ndomanyo/docker-tutorial-complex-react-test npm test
      - run: docker build -t ndomanyo/docker-tutorial-complex-client ./client
      - run: docker build -t ndomanyo/docker-tutorial-complex-nginx ./nginx
      - run: docker build -t ndomanyo/docker-tutorial-complex-server ./server
      - run: docker build -t ndomanyo/docker-tutorial-complex-worker ./worker
      - run: docker push ndomanyo/docker-tutorial-complex-client
      - run: docker push ndomanyo/docker-tutorial-complex-nginx
      - run: docker push ndomanyo/docker-tutorial-complex-server
      - run: docker push ndomanyo/docker-tutorial-complex-worker